# Generated by Django 3.2.23 on 2024-01-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
