# Generated by Django 3.2.23 on 2024-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='end',
        ),
        migrations.RemoveField(
            model_name='season',
            name='start',
        ),
        migrations.AddField(
            model_name='season',
            name='end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (0, 'Undefined')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='start_month',
            field=models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (0, 'Undefined')], default=0, null=True),
        ),
    ]
